### ISSUE TITLE
503 on libcaca homepage

### ISSUE THREAD

**Issue by alexvong1995** [cacalabs/libcaca#11]
Hi,

Accessing http://caca.zoy.org/wiki/libcaca leads to `503 - Service Not Available`. Is it a temporary failure? Is the homepage is being changed?

**Comment by samhocevar** [comment]
Someone reconfigured the web server but didn’t restart it properly; this is now fixed.

Note that yes, the homepage needs a massive cleanup and we should probably get rid of Trac now that I have accepted that GitHub works well. It just hasn’t happened yet.

**Comment by alexvong1995** [comment]
Thanks for the quick fix!
