### ISSUE TITLE
Setting the locale interferes with mpv

### ISSUE THREAD

**Issue by sotlampr** [cacalabs/libcaca#12]
Hello,

I noticed a bug when running mps-youtube with mpv on some occasions libcaca crashes mpv.

The source of the problem is that libcaca uses the setlocale function ([here](https://github.com/cacalabs/libcaca/blob/203d33361ee392588bcbd42684791460bf9cd35d/caca/driver/ncurses.c#L246) and [here](https://github.com/cacalabs/libcaca/blob/203d33361ee392588bcbd42684791460bf9cd35d/caca/driver/x11.c#L109)), and in languages that have comma as decimal mark this can lead to abnormal behavior.
The issue was also discussed [here](https://github.com/mpv-player/mpv/issues/2740).
Can you take a look at this?
S.

**Comment by samhocevar** [comment]
This is a bug in mpv but I’ll try to ensure libcaca restores the locale when it no longer needs it, so as to avoid the crash.

**Comment by wm4** [comment]
> This is a bug in mpv 

This is false.

>  but I’ll try to ensure libcaca restores the locale when it no longer needs it

This is pointless.

**Comment by samhocevar** [comment]
> > but I’ll try to ensure libcaca restores the locale when it no longer needs it

> This is pointless.

I do what I want and I get to decide whether it’s worth it. Enjoy not being a fun person! ♡

**Comment by wm4** [comment]
It's still pointless in a very technical way. Just because you switch temporarily, it doesn't mean that
1. another thread has called setlocale and ruined everything for you
2. another thread is using basic C string processing and gets everything ruined by your temporary setlocale call
Both of these could be race conditions quite awesome to debug

I'm sorry that you have to learn that your loved setlocal is INSANE.

**Comment by samhocevar** [comment]
You either misread or misunderstood, but that’s okay, I will do fine without your help, but thanks for trying! You can still reflect on your life and remember that you are the one using libcaca and lecturing me about “pointless”.

**Comment by wm4** [comment]
I might have misunderstood, but you're not clarifying anything, and I don't see to what else your plan to restore the locale was related to. Anyway, you show complete lack of understanding regarding library safety issues, and you're not showing any signs of trying (or even wanting) to understand them, so I guess I can't help you.

**Comment by samhocevar** [comment]
Excuse me, I didn’t see where you asked for clarification. I’ve only seen you claim my plans were pointless (without knowing the details), claim that I was going to do a temporary setlocale call (I won’t, I’ll be using uselocale, which didn’t exist when I wrote libcaca), claim that I love setlocale (I don’t, but it’s required for ncurses and Xlib to properly output some Unicode glyphs). I’m fixing my code. In the meantime, you can fix your attitude.

**Comment by wm4** [comment]
Alright. Sorry for extrapolating the worst implementation choice that could have taken.

**Comment by wm4** [comment]
I'm no sure why you need locale for X11, but never xlib versions have UTF-8 functions. (And then there's XCB.)
