### ISSUE TITLE
meson build system planned ?

### ISSUE THREAD

**Issue by vtorri** [cacalabs/libcaca#46]
Hello

is adding a meson build system planned ?

thank you

**Comment by rofl0r** [comment]
why is it that members of the cmake and meson cult go around lobbying users of other buildsystems to switch to theirs ? are you getting paid to do so ?

**Comment by vtorri** [comment]
i'm not paid (well, not for that...), but i currently have to use the git repo and for some technical reasons, the bootstrap script fails. So i wonder if another build system will be used.

I close this discussion
